### ISSUE TITLE
风扇中央不是一个完美的圆，导致头晕

### ISSUE THREAD

**Issue by JaySon-Huang** [ElpsyCN/electric-fan#10]
风扇中央不是一个完美的圆形，启动之后视线焦点随着小凸起转起来，感觉头晕目眩😵‍💫
![image](https://user-images.githubusercontent.com/4865550/117924459-59b48a80-b328-11eb-8a8b-f787f2e1a8f5.png)

**Comment by YunYouJun** [comment]
主要是由于浏览器 1px 问题造成的，通过缩小圆心边宽度为 10px 来修复。
