### ISSUE TITLE
打开时切换档位没有声音

### ISSUE THREAD

**Issue by HaneRo** [ElpsyCN/electric-fan#4]
必须停止后才有，另外声音像拖拉机，中间有断点
![Screenshot_20210510-215008__01](https://user-images.githubusercontent.com/26104114/117669728-cd944d00-b1d9-11eb-9521-e84f6a87cece.jpg)

**Comment by YunYouJun** [comment]
音效只有这个了，有更好的也欢迎推荐，切换开关的声音加上了。
